export const ADD_EDIT_ADMIN_USER_ACTION = 'ADD_ADMIN_USER_ACTION';
export const SET_ADMIN_USER_ACTION = 'SET_ADMIN_USER_ACTION';
export const ADD_SERVICE_ACTION = 'ADD_SERVICE_ACTION';
export const SET_SERVICE_ACTION = 'SET_SERVICE_ACTION';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const SET_APPOINTMENT_ACTION = 'SET_APPOINTMENT_ACTION';
export const SET_OPENING_HOURS_ACTION = 'SET_OPENING_HOURS_ACTION';
