export const ADD_ADMIN_USER_ACTION = 'ADD_ADMIN_USER_ACTION';
export const SET_ADMIN_USER_ACTION = 'SET_ADMIN_USER_ACTION';
export const STATUS_ADMIN_USER_ACTION = 'STATUS_ADMIN_USER_ACTION';
export const ADD_SERVICE_ACTION = 'ADD_SERVICE_ACTION';
export const SET_SERVICE_ACTION = 'SET_SERVICE_ACTION';
