<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRxDjVP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRxDjVP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXRxDjVP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXRxDjVP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXRxDjVP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XRxDjVP',
    'container.build_id' => 'b8b1cd74',
    'container.build_time' => 1559741719,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRxDjVP');
