<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AdminUserTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->apiUrl = 'api/adminUser';
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testGetEndpoint()
    {
//        $this->withoutExceptionHandling();
//        $user = factory('App\AdminUser', 1)->make();
//        $this->actingAs($user->first(), 'api');
//        $response = $this->get($this->apiUrl);
//        $response->assertStatus(200);
    }

    public function testPostEndpoint()
    {
//        $this->withoutExceptionHandling();
//        $user = factory('App\AdminUser', 1);
//        $this->actingAs($user->make()->first(), 'api');
//        $response = $this->post($this->apiUrl, $user->raw()[0]);
//        $response->assertStatus(200);
    }

}
